{"name": "Check that button works with different clicks", "status": "broken", "statusDetails": {"message": "ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zip", "trace": "@pytest.fixture()\n    def driver():\n        # driver = webdriver.Chrome(ChromeDriverManager(version='114.0.5735.90').install())\n        # driver.maximize_window()\n    \n        option = webdriver.ChromeOptions()\n        option.add_argument(\"start-maximized\")\n    \n>       driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=option)\n\nconftest.py:14: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nvenv\\Lib\\site-packages\\webdriver_manager\\chrome.py:39: in install\n    driver_path = self._get_driver_path(self.driver)\nvenv\\Lib\\site-packages\\webdriver_manager\\core\\manager.py:30: in _get_driver_path\n    file = self._download_manager.download_file(driver.get_url())\nvenv\\Lib\\site-packages\\webdriver_manager\\core\\download_manager.py:28: in download_file\n    response = self._http_client.get(url)\nvenv\\Lib\\site-packages\\webdriver_manager\\core\\http.py:33: in get\n    self.validate_response(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresp = <Response [404]>\n\n    @staticmethod\n    def validate_response(resp: requests.Response):\n        status_code = resp.status_code\n        if status_code == 404:\n>           raise ValueError(f\"There is no such driver by url {resp.url}\")\nE           ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zip\n\nvenv\\Lib\\site-packages\\webdriver_manager\\core\\http.py:16: ValueError"}, "start": 1691767064801, "stop": 1691767064801, "uuid": "243b57f2-2c81-467d-b678-fef03d73b6e4", "historyId": "5e6ab1a0516d0380aafb35fac9e57919", "testCaseId": "5e6ab1a0516d0380aafb35fac9e57919", "fullName": "tests.tests_elements.test_buttons.TestButtons#test_different_click_on_the_buttons", "labels": [{"name": "feature", "value": "Buttons"}, {"name": "parentSuite", "value": "tests.tests_elements"}, {"name": "suite", "value": "test_buttons"}, {"name": "subSuite", "value": "TestButtons"}, {"name": "host", "value": "TX-N-0684"}, {"name": "thread", "value": "23216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_elements.test_buttons"}]}